/// Flutter icons WeatherIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcon
///      fonts:
///       - asset: fonts/WeatherIcon.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class WeatherIcon {
  WeatherIcon._();

  static const _kFontFam = 'WeatherIcon';
  static const String? _kFontPkg = null;

  static const IconData rain_inv = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
